# Generated by Django 5.2.11 on 2026-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='student_images/')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('Math', 'Mathematics'), ('Science', 'Science'), ('History', 'History'), ('Literature', 'Literature')], max_length=20)),
            ],
        ),
    ]
